In [88]:
import pandas as pd
import sqlite3

In [89]:
connMedicalData = sqlite3.connect('db/medical_data.db')
connHPOAnnots = sqlite3.connect('assets/HPO/hpo_annotations.sqlite')

# Exploration des données SIDER

In [90]:
dataset_indicationsHeal = pd.read_csv('assets/SIDER/meddra_all_indications.tsv', sep='\t', names=["drug_id_stereo", "umls_id", "method", "symptom", "meddra_type", "meddra_umls_id", "meddra_official_name"])
dataset_indicationsHeal

,drug_id_stereo,umls_id,method,symptom,meddra_type,meddra_umls_id,meddra_official_name
0,CID100000085,C0015544,text_mention,Failure to Thrive,LLT,C0015544,Failure to thrive
1,CID100000085,C0015544,text_mention,Failure to Thrive,PT,C0015544,Failure to thrive
2,CID100000085,C0020615,text_mention,Hypoglycemia,LLT,C0020615,Hypoglycaemia
3,CID100000085,C0020615,text_mention,Hypoglycemia,PT,C0020615,Hypoglycaemia
4,CID100000085,C0022661,NLP_indication,"Kidney Failure, Chronic",LLT,C0022661,Renal failure chronic
...,...,...,...,...,...,...,...
30830,CID171306834,C0524910,NLP_precondition,"Hepatitis C, Chronic",PT,C0524910,Chronic hepatitis C
30831,CID171306834,C0741132,text_mention,Antibody test positive,LLT,C0741132,Antibody test positive
30832,CID171306834,C0741132,text_mention,Antibody test positive,PT,C0741132,Antibody test positive
30833,CID171306834,C0856536,text_mention,Philadelphia chromosome positive,LLT,C0856536,Philadelphia chromosome positive
30834,CID171306834,C0856536,text_mention,Philadelphia chromosome positive,PT,C0476431,Chromosome analysis abnormal

In [91]:
dataset_secondaries = pd.read_csv('assets/SIDER/meddra_all_se.tsv', sep='\t', names=["drug_id_stereo", "drug_id_flat", "umls_id", "meddra_type", "meddra_umls_id", "meddra_official_name"])
dataset_secondaries

,drug_id_stereo,drug_id_flat,umls_id,meddra_type,meddra_umls_id,meddra_official_name
0,CID100000085,CID000010917,C0000729,LLT,C0000729,Abdominal cramps
1,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain
2,CID100000085,CID000010917,C0000737,LLT,C0000737,Abdominal pain
3,CID100000085,CID000010917,C0000737,PT,C0687713,Gastrointestinal pain
4,CID100000085,CID000010917,C0000737,PT,C0000737,Abdominal pain
...,...,...,...,...,...,...
309844,CID171306834,CID071306834,C3203358,PT,C1145670,Respiratory failure
309845,CID171306834,CID071306834,C3665386,LLT,C3665386,Abnormal vision
309846,CID171306834,CID071306834,C3665386,PT,C3665347,Visual impairment
309847,CID171306834,CID071306834,C3665596,LLT,C3665596,Warts
309848,CID171306834,CID071306834,C3665596,PT,C0347390,Skin papilloma

In [92]:
dataset_secondaryFreq = pd.read_csv('assets/SIDER/meddra_freq.tsv', sep='\t', names=["drug_id_stereo", "drug_id_flat", "meddra_umls_id", "experiment", "frequency", "lower_bound", "upper_bound", "meddra_type", "umls_id", "meddra_official_name"])
dataset_secondaryFreq

,drug_id_stereo,drug_id_flat,meddra_umls_id,experiment,frequency,lower_bound,upper_bound,meddra_type,umls_id,meddra_official_name
0,CID100000085,CID000010917,C0000737,NaN,21%,0.21,0.21,LLT,C0000737,Abdominal pain
1,CID100000085,CID000010917,C0000737,NaN,21%,0.21,0.21,PT,C0000737,Abdominal pain
2,CID100000085,CID000010917,C0000737,NaN,21%,0.21,0.21,PT,C0687713,Gastrointestinal pain
3,CID100000085,CID000010917,C0000737,NaN,5%,0.05,0.05,LLT,C0000737,Abdominal pain
4,CID100000085,CID000010917,C0000737,NaN,5%,0.05,0.05,PT,C0000737,Abdominal pain
...,...,...,...,...,...,...,...,...,...,...
291627,CID171306834,CID071306834,C2830004,NaN,5%,0.00,0.05,PT,C2830004,Somnolence
291628,CID171306834,CID071306834,C2830004,NaN,5%,0.05,0.05,LLT,C2830004,Somnolence
291629,CID171306834,CID071306834,C2830004,NaN,5%,0.05,0.05,PT,C2830004,Somnolence
291630,CID171306834,CID071306834,C2830004,NaN,9%,0.09,0.09,LLT,C2830004,Somnolence
291631,CID171306834,CID071306834,C2830004,NaN,9%,0.09,0.09,PT,C2830004,Somnolence

In [93]:
dataset_link_umls_meddra = pd.read_csv('assets/SIDER/meddra.tsv', sep='\t', names=["umls_id", "meddra_type", "meddra_id", "meddra_official_name"])
dataset_link_umls_meddra

        umls_id meddra_type  meddra_id         meddra_official_name
0      C0000727          LT   10000647                Acute abdomen
1      C0000727          PT   10000647                Acute abdomen
2      C0000727          LT   10042784     Syndrome abdominal acute
3      C0000727          LT   10000096     Abdominal syndrome acute
4      C0000729          LT   10000057             Abdominal cramps
...         ...         ...        ...                          ...
95907  C3666015          LT   10074155  Device material degradation
95908  C3666016          LT   10074210         Coarse breath sounds
95909  C3666017          LT   10074226               Cholangiopathy
95910  C3666018          LT   10074267      Spontaneous ejaculation
95911  C3666018          PT   10074267      Spontaneous ejaculation

[95912 rows x 4 columns]

In [94]:
for table in ["indications", "secondaries", "frequencies", "umls_meddra"]:
    connMedicalData.execute(f"DROP TABLE IF EXISTS {table}")

dataset_indicationsHeal.to_sql('indications', connMedicalData, index=False)
dataset_secondaries.to_sql('secondaries', connMedicalData, index=False)
dataset_secondaryFreq.to_sql('frequencies', connMedicalData, index=False)
dataset_link_umls_meddra.to_sql('umls_meddra', connMedicalData, index=False)

95912

Recherche d'effets secondaires par symptôme:

In [95]:
query = """
SELECT DISTINCT drug_id_stereo, meddra_official_name AS side_effects
FROM secondaries
WHERE secondaries.umls_id = 'C0000729'
"""

df_side_effects = pd.read_sql_query(query, connMedicalData)
df_side_effects

    drug_id_stereo      side_effects
0     CID100000085  Abdominal cramps
1     CID100000085    Abdominal pain
2     CID100000450  Abdominal cramps
3     CID100000450    Abdominal pain
4     CID100000698  Abdominal cramps
..             ...               ...
195   CID105327147    Abdominal pain
196   CID111979316  Abdominal cramps
197   CID111979316    Abdominal pain
198   CID116129665  Abdominal cramps
199   CID116129665    Abdominal pain

[200 rows x 2 columns]

Recherche d'effets secondaires par médicament:

In [96]:
query = """
SELECT DISTINCT drug_id_stereo, meddra_official_name AS side_effects
FROM secondaries
WHERE secondaries.drug_id_stereo = 'CID100000085'
"""

df_side_effects = pd.read_sql_query(query, connMedicalData)
df_side_effects

   drug_id_stereo           side_effects
0    CID100000085       Abdominal cramps
1    CID100000085         Abdominal pain
2    CID100000085  Gastrointestinal pain
3    CID100000085              Amblyopia
4    CID100000085                Anaemia
..            ...                    ...
73   CID100000085         Fluid overload
74   CID100000085               Insomnia
75   CID100000085             Myasthenia
76   CID100000085      Muscular weakness
77   CID100000085        Drug dependence

[78 rows x 2 columns]

# Exploration données HPO

In [97]:
import re

cursor = connMedicalData.cursor()
cursor.execute("""
    CREATE TABLE IF NOT EXISTS hpo_terms (
        hpo_id TEXT PRIMARY KEY,
        name TEXT,
        synonyms TEXT
    )
""")

with open("assets/HPO/hpo.obo", "r", encoding="utf-8") as f:
    content = f.read().split("[Term]")
    for term in content[1:]:
        hpo_id_match = re.search(r"^id: (HP:\d+)", term, re.M)
        name_match = re.search(r"^name: (.*)", term, re.M)

        if hpo_id_match and name_match:
            hpo_id = hpo_id_match.group(1)
            name = name_match.group(1).lower()
            synonyms = "|".join(re.findall(r'synonym: "(.*)"', term)).lower()
            cursor.execute(
                "INSERT OR REPLACE INTO hpo_terms VALUES (?, ?, ?)",
                (hpo_id, name, synonyms),
            )

connMedicalData.commit()

In [98]:
#Select all synonyms of a secondary effect. Retrieve the secondary effect ID
connMedicalData.execute("SELECT * FROM hpo_terms WHERE name='fever'").fetchall()

[('HP:0001945', 'fever', 'fever|hyperthermia|pyrexia')]

In [99]:
connMedicalData.close()

In [100]:
#Get the effects name & OMIM id of the medicaments corresponding to the side effects
connHPOAnnots.execute("SELECT disease_db_and_id, disease_label FROM phenotype_annotation WHERE sign_id = 'HP:0001945' LIMIT 1").fetchall()

[('OMIM:108050',
  'ARTERITIS, FAMILIAL GRANULOMATOUS, WITH JUVENILE POLYARTHRITIS')]

# Exploration OMIM à partir de HPO

In [101]:
omim_dataset = pd.read_csv("assets/OMIM/omim_onto.csv")
omim_dataset

,Class ID,Preferred Label,Synonyms,Definitions,Obsolete,CUI,Semantic Types,Parents
0,http://purl.bioontology.org/ontology/OMIM/600374,BBS4 GENE,BBS4,NaN,False,C1412749,http://purl.bioontology.org/ontology/STY/T028,NaN
1,http://purl.bioontology.org/ontology/OMIM/MTHU...,Hypoplastic ilia,NaN,NaN,False,C1846800,http://purl.bioontology.org/ontology/STY/T033,http://purl.bioontology.org/ontology/OMIM/MTHU...
2,http://purl.bioontology.org/ontology/OMIM/MTHU...,Reduced number of memory B cells,NaN,NaN,False,C3278889,http://purl.bioontology.org/ontology/STY/T033,http://purl.bioontology.org/ontology/OMIM/MTHU...
3,http://purl.bioontology.org/ontology/OMIM/606301,"PROTOCADHERIN-GAMMA, SUBFAMILY B, MEMBER 3",PCDHGB3|PCDH-GAMMA-B3,NaN,False,C1418359,http://purl.bioontology.org/ontology/STY/T028,NaN
4,http://purl.bioontology.org/ontology/OMIM/614769,"CYTOCHROME C OXIDASE ASSEMBLY FACTOR 1, S. CER...",C7ORF44|CHROMOSOME 7 OPEN READING FRAME 44|COA...,NaN,False,C1824229,http://purl.bioontology.org/ontology/STY/T028,NaN
...,...,...,...,...,...,...,...,...
76712,http://purl.bioontology.org/ontology/OMIM/613968,"TASTE RECEPTOR, TYPE 2, MEMBER 60",T2R60|TAS2R60,NaN,False,C1427048,http://purl.bioontology.org/ontology/STY/T028,NaN
76713,http://purl.bioontology.org/ontology/OMIM/6026...,NATURAL KILLER CELL AND GLUCOCORTICOID DEFICIE...,"MCM4, IVS1AS, A-G, -2",NaN,False,C3551444,http://purl.bioontology.org/ontology/STY/T028,NaN
76714,http://purl.bioontology.org/ontology/OMIM/3000...,"RETT SYNDROME, ZAPPELLA VARIANT, 44-BP DEL, NT...","MECP2, 44-BP DEL, NT1159",NaN,False,C1848369,http://purl.bioontology.org/ontology/STY/T028,NaN
76715,http://purl.bioontology.org/ontology/OMIM/147400,"INCISORS, SHOVEL-SHAPED",SINODONTY,NaN,False,C1409763,http://purl.bioontology.org/ontology/STY/T019,NaN
76716,http://purl.bioontology.org/ontology/OMIM/1576...,"CARTILAGE-HAIR HYPOPLASIA, 18-BP DUP, NT-3","RMRP, 18-BP DUP, NT-3",NaN,False,C1834827,http://purl.bioontology.org/ontology/STY/T028,NaN

In [102]:
omim_file = open("assets/OMIM/omim.txt", "r", encoding="utf-8").read().split("\n")
omim_file[:10]

['*RECORD*',
 '*FIELD* NO',
 '100050',
 '*FIELD* TI',
 '100050 AARSKOG SYNDROME, AUTOSOMAL DOMINANT',
 '*FIELD* TX',
 '',
 'DESCRIPTION',
 '',
 'Aarskog syndrome is characterized by short stature and facial, limb, and']

On aperçoit que les données OMIM sont organisées en sections, chaque section correspondant à une maladie. Chaque section commence par un identifiant de maladie (ex: 100100) suivi de différentes propriétés (ex: Titre, Symptômes, etc.).

In [103]:
omim_id = "108050"
details = {"id": omim_id, "symptoms": [], "title": ""}

found = False
current_field = None

with open("assets/OMIM/omim.txt", 'r', encoding='utf-8') as f:
    for raw in f:
        line = raw.rstrip("\n")

        # nv maladie
        if line.startswith('*RECORD*'):
            found = False
            current_field = None
            continue

        # maladie est celle recherchée
        if not found and line.strip() == omim_id:
            found = True
            continue

        if not found:
            continue

        if line[:7] == '*FIELD*':
            if line[8:10] == 'TI':
                current_field = 'TI'
                continue
            elif line[8:10] == 'CS':
                current_field = 'CS'
                continue
            else:
                current_field = None
                continue

        if current_field == 'TI':
            details["title"] = line.strip()
        elif current_field == 'CS':
            if line.strip():
                details["symptoms"].append(line.strip())

# result
details

{'id': '108050',
 'symptoms': ['Endo:',
  'Hypertension',
  'Joints:',
  'Juvenile polyarthritis;',
  'Rheumatoid arthritis',
  'Skin:',
  'Macular erythematous rash;',
  'Subcutaneous nodules;',
  'Jaundice',
  'Cardiac:',
  'Pericardial effusion;',
  'Granulomatous coronary arteritis',
  'Neuro:',
  'Headache;',
  'Seizures',
  'Eyes:',
  'Iritis;',
  'Papilledema',
  'Pulmonary:',
  'Pleural effusion',
  'Misc:',
  'Fever',
  'Radiology:',
  'Abdominal aortograms show beading of the splenic, renal and iliac',
  'arteries, proximal stenosis and poststenotic dilatation, and intrarenal',
  'arterial stenoses',
  'Lab:',
  'Noncaseating granulomas, vascular and extravascular esp;',
  'hepatic;',
  'Elevated alkaline phosphatase',
  'Inheritance:',
  'Autosomal dominant'],
 'title': '108050 ARTERITIS, FAMILIAL GRANULOMATOUS, WITH JUVENILE POLYARTHRITIS'}